{% set name = "kerchunk" %}
{% set version = "0.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kerchunk-{{ version }}.tar.gz
  sha256: 10da10dfcf589352885a5e110c3c458852935e0c2e08153a857093b880fbc98c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - fsspec
    - python >=3.7
    - ujson
    - zarr

test:
  imports:
    - kerchunk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fsspec/kerchunk
  summary: Functions to make reference descriptions for ReferenceFileSystem
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - martindurant
    - rsignell-usgs
