{% set name = "kerchunk" %}
{% set version = "0.0.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kerchunk-{{ version }}.tar.gz
  sha256: 110d55a53818dedb4be0cbf7743db85413dc7393b2f2e8a9210d5a6a8fe93a21

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - fsspec
    - python >=3.7
    - ujson

test:
  imports:
    - fsspec_reference_maker
    - kerchunk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fsspec/kerchunk
  summary: Functions to make reference descriptions for ReferenceFileSystem
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - martindurant
    - rsignell-usgs

