{% set name = "kerchunk" %}
{% set version = "0.0.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kerchunk-{{ version }}.tar.gz
  sha256: 78d8ed8ff19bc76b53b8baa03f511e2cd020ad9f60fbba8a251a54e568d48c31

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - fsspec
    - python >=3.7
    - ujson

test:
  imports:
    - fsspec_reference_maker
    - kerchunk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fsspec/kerchunk
  summary: Functions to make reference descriptions for ReferenceFileSystem
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - martindurant
    - rsignell-usgs

